const List<String> pokharaLocations = [
  'Amarsingh Chowk, Pokhara',
  'Annapurna Base Camp, Pokhara',
  'Bagar, Pokhara',
  'Banjaar, Pokhara',
  'Batulechaur, Pokhara',
  'Begnas Bazar, Pokhara',
  'Begnas Lake, Pokhara',
  'Begnas Tal, Pokhara',
  'Bhadure, Pokhara',
  'Bhadaure Tamagi, Pokhara',
  'Bhalam, Pokhara',
  'Bhimad, Pokhara',
  'Birkot, Pokhara',
  'Birethanti, Pokhara',
  'Birauta, Pokhara',
  'Bramhachhetra, Pokhara',
  'Buddhachowk, Pokhara',
  'Chapakot, Pokhara',
  'Chhorepatan, Pokhara',
  'Chhorepatan Ganesh Temple, Pokhara',
  'Chipledhunga, Pokhara',
  'Chitre, Pokhara',
  'Chokramudi, Pokhara',
  'Damachaur, Pokhara',
  'Damside, Pokhara',
  'Dana, Pokhara',
  'Darau, Pokhara',
  'Deurali, Pokhara',
  'Devi\'s Fall, Pokhara',
  'Dhampus, Pokhara',
  'Fulbari, Pokhara',
  'Gandaki Medical College, Pokhara',
  'Ghatichina, Pokhara',
  'Ghachok, Pokhara',
  'Ghachowk, Pokhara',
  'Ghandruk, Pokhara',
  'Gulmi, Pokhara',
  'Gurung Village, Pokhara',
  'Hari Chowk, Pokhara',
  'Harihar Kund, Pokhara',
  'Harpak, Pokhara',
  'Hemja, Pokhara',
  'Jaimini, Pokhara',
  'Jaljala, Pokhara',
  'Jamune, Pokhara',
  'Jana, Pokhara',
  'Jhallar, Pokhara',
  'Jumla, Pokhara',
  'Kahunkhola, Pokhara',
  'Kaskikot, Pokhara',
  'Khahare, Pokhara',
  'Kusma Bazar, Pokhara',
  'Lakeside, Pokhara',
  'Lamachaur, Pokhara',
  'Lamakhet, Pokhara',
  'Lavand, Pokhara',
  'Lekhnath, Pokhara',
  'Machhapuchchhre Base Camp, Pokhara',
  'Madan Pokhari, Pokhara',
  'Mahashila, Pokhara',
  'Mahendrapool, Pokhara',
  'Malepatan, Pokhara',
  'Mardi, Pokhara',
  'Majhakot, Pokhara',
  'Majhuwa, Pokhara',
  'Malarani, Pokhara',
  'Manabir, Pokhara',
  'Matepani Gumba, Pokhara',
  'Masbar, Pokhara',
  'Mustang Chowk, Pokhara',
  'Nagdhunga, Pokhara',
  'Naudanda, Pokhara',
  'Nayabazar, Pokhara',
  'Nayapul, Pokhara',
  'New Road, Pokhara',
  'Nirmal Pokhari, Pokhara',
  'Painyu, Pokhara',
  'Palakot, Pokhara',
  'Panja, Pokhara',
  'Pame, Pokhara',
  'Pawannagar, Pokhara',
  'Phewa Lake, Pokhara',
  'Phusre, Pokhara',
  'Pokhara Airport, Pokhara',
  'Pokhara Industrial Area, Pokhara',
  'Pokhara Metropolitan City Hall, Pokhara',
  'Pokhara Stadium, Pokhara',
  'Pokhara University, Pokhara',
  'Prithvi Chowk, Pokhara',
  'Pumdikot, Pokhara',
  'Puranchaur, Pokhara',
  'Raisethor, Pokhara',
  'Rambazar, Pokhara',
  'Ranabhim, Pokhara',
  'Ranipani, Pokhara',
  'Ranipauwa, Pokhara',
  'Rastrabank Chowk, Pokhara',
  'Rim, Pokhara',
  'Rhimu, Pokhara',
  'Rishi Panchami Bazaar, Pokhara',
  'Ritha, Pokhara',
  'Rudrapur, Pokhara',
  'Rupa Lake, Pokhara',
  'Rupa Tal, Pokhara',
  'Rupakot, Pokhara',
  'Sabhung, Pokhara',
  'Saipal, Pokhara',
  'Salyan, Pokhara',
  'Sanothimi, Pokhara',
  'Sarangkot, Pokhara',
  'Sarangkot Hill, Pokhara',
  'Seti Gandaki Hydroelectric Plant, Pokhara',
  'Shanti Stupa, Pokhara',
  'Sharanpur, Pokhara',
  'Shukla Gandaki Hydroelectric Plant, Pokhara',
  'Shuklagandaki, Pokhara',
  'Siddha Cave, Pokhara',
  'Sikles, Pokhara',
  'Siklis, Pokhara',
  'Sildujure, Pokhara',
  'Simalchaur, Pokhara',
  'Simaltar, Pokhara',
  'Simikot, Pokhara',
  'Sirubari, Pokhara',
  'Swargadwari, Pokhara',
  'Tachapal, Pokhara',
  'Tal Barahi Temple, Pokhara',
  'Talchowk, Pokhara',
  'Talghare, Pokhara',
  'Tawal, Pokhara',
  'Thak Chok, Pokhara',
  'Tibetan Camp, Pokhara',
  'Tumlingtar, Pokhara',
  'Uttarganga, Pokhara',
  'Valpar, Pokhara',
  'Vimkot, Pokhara',
  'Western Regional Hospital, Pokhara',
  'World Peace Pagoda, Pokhara',
  'Yamgha, Pokhara',
  'Yarsha, Pokhara',
  'Yunubani, Pokhara',
  'Zero Kilometer, Pokhara',
];
